using UnityEngine;
using System.Collections;
using System;

public class instruction : MonoBehaviour {

//this defines the code used by .3da file types which are going to be sent directly to the arduino and 3D Robot to be executed and build something 
//based upon what is generated by this program

    public string movegimbal(int numgimbal, Vector3 position, Vector3 rotation)
    {
        string returnstring = "";
        returnstring = "G" + numgimbal.ToString() + " X" + position.x.ToString() + " Y" + position.y.ToString() +
            " Z" + position.z.ToString() + " RX" + rotation.x.ToString() + " RY" + rotation.y.ToString() + " RZ" + rotation.z.ToString() + Environment.NewLine;
        return returnstring;

    }

    public string connector(int numconnector, bool onoroff)
    {
        string returnstring = "";
        if (onoroff)
        {
            returnstring = "C1"; 
                }
        else
        {
            returnstring = "C0";
        }
        returnstring = returnstring + " G" + numconnector.ToString();
        return returnstring;
    }

    public string controltoolend(int numconnector, bool poweron)
    {
        string returnstring = "";
        if(poweron)
        {
            returnstring = "T1";
        }
        else
        {
            returnstring = "T0";
        }
        returnstring = returnstring + " G" + numconnector.ToString();
        return returnstring;
    }
}
